train_src: /home/hungphd/git/dataPapers/SPOCDataset/spoc/input-tok-train-shuf.tsv
train_tgt: "-"
valid_src: /home/hungphd/git/dataPapers/SPOCDataset/spoc/input-tok-eval.tsv
valid_tgt: "-"
save_data: out/preprocessed
dynamic_dict: true
