src: /home/hungphd/git/dataPapers/SPOCDataset/spoc/input-tok-test-src.tsv
tgt: /home/hungphd/git/dataPapers/SPOCDataset/spoc/input-tok-test-tgt.tsv
output: /home/hungphd/git/dataPapers/SPOCDataset/spoc/outputFromConfig.txt

replace_unk: true
verbose: true
beam_size: 100
n_best: 100
gpu: 0
batch_size: 200     # Use 1 for large beam_size (~1000), reduces memory load
